Repository bajo1207/piggymetrics, pull requests merged in 2020-01, with the labels that each got.

#27 Connect w pay pal support
  gateway/src/main/resources/static/index.html
  piggypal/Controllers/Main_controller.py
  piggypal/Dockerfile
  piggypal/Views/index.html
  piggypal/src/Configs/Server.conf
  piggypal/src/Configs/example.conf
  piggypal/src/Configs/piggypal.conf
  piggypal/src/Controllers/Main_controller.py
  piggypal/src/Models/Paypal_api_stub.py
  piggypal/src/Run.py
  piggypal/src/Views/Login_button.py
  piggypal/src/Views/login.html
Labels: enhancement

#28 Update general CI/CDE settings
  .travis.yml
  docker-compose.yml
Labels: Infrastructure, enhancement

#29 In-between merge to reestablish piggypal button-call functionality
  piggypal/src/Controllers/Main_controller.py
  piggypal/src/Views/login.html
  piggypal/src/main/Configs/Server.conf
  piggypal/src/main/Configs/example.conf
  piggypal/src/main/Configs/piggypal.conf
  piggypal/src/main/Controllers/Main_controller.py
  piggypal/src/main/Models/Paypal_api_stub.py
  piggypal/src/main/Run.py
  piggypal/src/main/Views/Login_button.py
  piggypal/src/main/Views/login.html
Labels: bug

#30 Piggypal testing
  README.md
  gateway/src/main/resources/static/index.html
  piggypal/Dockerfile
  piggypal/src/Controllers/Main_controller.py
  piggypal/src/Views/login.html
  piggypal/src/main/Configs/Server.conf
  piggypal/src/main/Configs/example.conf
  piggypal/src/main/Configs/piggypal.conf
  piggypal/src/main/Controllers/Main_controller.py
  piggypal/src/main/Models/Paypal_api_stub.py
  piggypal/src/main/Run.py
  piggypal/src/main/Views/Login_button.py
  piggypal/src/main/Views/login.html
Labels: bug

#33 Travis ci
  .travis.yml
  build.sh
  deploy.sh
  piggypal/Dockerfile
  piggypal/src/main/Configs/example.conf
  piggypal/src/main/Configs/piggypal.conf
  piggypal/src/main/Controllers/Main_controller.py
  piggypal/src/main/Models/Paypal_api_stub.py
  piggypal/src/main/Run.py
  piggypal/src/main/Views/Login_button.py
  test.sh
Labels: Infrastructure, enhancement

#34 Documentation s3
  .travis.yml
Labels: Infrastructure, documentation, enhancement

#35 Code documentation
  docker-compose.yml
  gateway/src/main/resources/static/index.html
  piggypal/src/main/Doc/main/Controllers/Main_controller.html
  piggypal/src/main/Doc/main/Controllers/index.html
  piggypal/src/main/Doc/main/Models/Paypal_api_stub.html
  piggypal/src/main/Doc/main/Models/index.html
  piggypal/src/main/Doc/main/Run.html
  piggypal/src/main/Doc/main/Views/Login_button.html
  piggypal/src/main/Doc/main/Views/index.html
  piggypal/src/main/Doc/main/index.html
  piggypal/src/main/Models/Paypal_api_stub.py
  piggypal/src/main/Run.py
  piggypal/src/main/Views/Login_button.py
Labels: documentation

#40 Readme user workflow
  README.md
Labels: documentation

#39 update master
  gateway/src/main/resources/static/index.html
  gateway/src/main/resources/static/login.html
  piggypal/src/main/Models/Paypal_api_stub.py
Labels: Infrastructure, documentation

#41 Fix: Dockerfile environment
  piggypal/Dockerfile
Labels: bug

#42 Travis tests
  .travis.yml
  piggypal/src/main/Run.py
  pytests.sh
  test.sh
Labels: Infrastructure, enhancement
